version: 2

models:
  # ---------------- STAGING ----------------
  - name: stg_trips
    tests:
      - not_null:
          arguments:
            column_name: dup_key
      - unique:
          arguments:
            column_name: dup_key
      # Custom macro you already have (kept as-is)
      - fare_within_tolerance:
          arguments:
            actual_col: manual_total
            expected_col: total_amount
            tolerance: 0.50

  # ---------------- DIMENSIONS ----------------
  - name: dim_date
    tests:
      - not_null:
          arguments:
            column_name: date_day
      - unique:
          arguments:
            column_name: date_day

  - name: dim_payment
    tests:
      - not_null:
          arguments:
            column_name: payment_type
      - unique:
          arguments:
            column_name: payment_type
      - accepted_values:
          arguments:
            column_name: payment_type
            values: [1, 2, 3, 4, 5, 6]

  - name: dim_vendor
    tests:
      - not_null:
          arguments:
            column_name: vendor_id
      - unique:
          arguments:
            column_name: vendor_id

  - name: dim_zone
    tests:
      - not_null:
          arguments:
            column_name: location_id
      - unique:
          arguments:
            column_name: location_id

  # ---------------- FACTS ----------------
  - name: fact_trips
    tests:
      - relationships:
          arguments:
            column_name: date_day
            to: ref('dim_date')
            field: date_day
      - relationships:
          arguments:
            column_name: vendor_id
            to: ref('dim_vendor')
            field: vendor_id
      - relationships:
          arguments:
            column_name: payment_type
            to: ref('dim_payment')
            field: payment_type
      - relationships:
          arguments:
            column_name: pu_location_id
            to: ref('dim_zone')
            field: location_id
      - relationships:
          arguments:
            column_name: do_location_id
            to: ref('dim_zone')
            field: location_id

  - name: fact_revenue_adjustments
    tests:
      - relationships:
          arguments:
            column_name: date_day
            to: ref('dim_date')
            field: date_day
      - relationships:
          arguments:
            column_name: payment_type
            to: ref('dim_payment')
            field: payment_type
      - relationships:
          arguments:
            column_name: pu_location_id
            to: ref('dim_zone')
            field: location_id
      - relationships:
          arguments:
            column_name: do_location_id
            to: ref('dim_zone')
            field: location_id

  # ---------------- MARTS ----------------
  - name: mart_kpi_daily
    tests:
      - not_null:
          arguments:
            column_name: date_day
      - unique:
          arguments:
            column_name: date_day
      - relationships:
          arguments:
            column_name: date_day
            to: ref('dim_date')
            field: date_day

  - name: mart_revenue_daily_zone
    tests:
      - not_null:
          arguments:
            column_name: date_day
      - not_null:
          arguments:
            column_name: location_id
      - relationships:
          arguments:
            column_name: date_day
            to: ref('dim_date')
            field: date_day
      - relationships:
          arguments:
            column_name: location_id
            to: ref('dim_zone')
            field: location_id
      # We avoid dbt-utils; uniqueness is checked per (date_day, location_id)
      # by asserting both are not null and relationship-tested above.

  - name: mart_trips_hourly_vendor
    tests:
      - not_null:
          arguments:
            column_name: hour
      - not_null:
          arguments:
            column_name: vendor_id
      - relationships:
          arguments:
            column_name: vendor_id
            to: ref('dim_vendor')
            field: vendor_id

  - name: mart_payment_mix_daily
    tests:
      - not_null:
          arguments:
            column_name: date_day
      - not_null:
          arguments:
            column_name: payment_type
      - relationships:
          arguments:
            column_name: payment_type
            to: ref('dim_payment')
            field: payment_type
      - relationships:
          arguments:
            column_name: date_day
            to: ref('dim_date')
            field: date_day

  - name: mart_vendor_scorecard_monthly
    tests:
      - not_null:
          arguments:
            column_name: year_month
      - not_null:
          arguments:
            column_name: vendor_id
      - relationships:
          arguments:
            column_name: vendor_id
            to: ref('dim_vendor')
            field: vendor_id

  - name: mart_od_matrix_monthly
    tests:
      - not_null:
          arguments:
            column_name: year_month
      - relationships:
          arguments:
            column_name: pu_location_id
            to: ref('dim_zone')
            field: location_id
      - relationships:
          arguments:
            column_name: do_location_id
            to: ref('dim_zone')
            field: location_id

  - name: mart_adjustments_daily_zone
    tests:
      - not_null:
          arguments:
            column_name: date_day
      - not_null:
          arguments:
            column_name: location_id
      - relationships:
          arguments:
            column_name: date_day
            to: ref('dim_date')
            field: date_day
      - relationships:
          arguments:
            column_name: payment_type
            to: ref('dim_payment')
            field: payment_type
      - relationships:
          arguments:
            column_name: location_id
            to: ref('dim_zone')
            field: location_id

  - name: mart_congestion_impact_daily
    tests:
      - not_null:
          arguments:
            column_name: date_day
      - relationships:
          arguments:
            column_name: date_day
            to: ref('dim_date')
            field: date_day

  - name: mart_airport_daily
    tests:
      - not_null:
          arguments:
            column_name: date_day
      - accepted_values:
          arguments:
            column_name: direction
            values: ['PU', 'DO']

  - name: mart_anomaly_summary_daily
    tests:
      - not_null:
          arguments:
            column_name: date_day
      - relationships:
          arguments:
            column_name: date_day
            to: ref('dim_date')
            field: date_day
      - relationships:
          arguments:
            column_name: location_id
            to: ref('dim_zone')
            field: location_id
