name: "nyc_taxi_duckdb"
version: "1.0.0"
config-version: 2

profile: "nyc_taxi_duckdb"

# 👇 Point at the subfolders inside ./dbt
model-paths: ["dbt/models"]
seed-paths: ["dbt/seeds"]
macro-paths: ["dbt/macros"]

models:
  nyc_taxi_duckdb:
    staging:
      +materialized: view
    gold:
      +schema: gold
      +materialized: table
    marts:
      +schema: marts
      +materialized: table

seeds:
  nyc_taxi_duckdb:
    +schema: seeds
